### ISSUE TITLE
RuntimeException: java.lang.NoSuchMethodException

### ISSUE THREAD

**Issue by zoey-juan** [davidvavra/showkase-screenshot-tests#1]
Hi!
I tried to run the tests under this repository. However, I am getting those errors. Have you facing this issue? (As I know there is this issue report to facebook screenshot lib but I can't find the solution) Could you please share how to solve this issue? Thanks!
```
me.vavra.showkase.ComposeTests_ShowkaseCodegen > composable_screenshot_test_0[Pixel_3_API_28(AVD) - 9] FAILED 
        java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NoSuchMethodException: <init> [class android.content.Context, class android.view.Display]
        at com.facebook.testing.screenshot.internal.ScreenshotImpl.runCallableOnUiThread(ScreenshotImpl.java:349)
me.vavra.showkase.ViewTests > doScreenshot[Pixel_3_API_28(AVD) - 9] FAILED 
        java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NoSuchMethodException: <init> [class android.content.Context, class android.view.Display]
        at com.facebook.testing.screenshot.internal.ScreenshotImpl.runCallableOnUiThread(ScreenshotImpl.java:349)
```

**Comment by davidvavra** [comment]
Hi, unfortunately Facebook's lib has a maxSdk of 27. Try running it with emulator API 27.
